##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
url: https://marktwainhm.github.io/ithappenedinhartford/ 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: It Happened in Hartford
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: 150 Years of the Mark Twain House 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "September 2024 marks the 150th anniversary of the arrival of the Clemens family in their newly
constructed Hartford home….."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Mark Twain House & Museum

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: mthm-metadata
collections:
  towns:
    output: true
    permalink: /:collection/:title
  exhibits:
    output: true
    permalink: /:collection/:title

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
organization-name: "The Mark Twain House and Museum"
organization-link: https://marktwainhouse.org/
organization-logo-banner: https://marktwainhouse.org/wp-content/themes/jb-marktwain-2017/images/MarkTwainLogo.svg
organization-logo-nav: https://marktwainhouse.org/wp-content/themes/jb-marktwain-2017/images/MarkTwainLogo.svg
facebook: https://www.facebook.com/MarkTwainHouse/
instagram: https://www.instagram.com/themarktwainhouse/
twitter: https://twitter.com/twainhouse


##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "G-123XXXXXX"
google-analytics-id: G-BGV7FJKC4F
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
google-cse-id: 86326084b22364fbe

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
